### ISSUE TITLE
Add an option to control verbosity

### ISSUE THREAD

**Issue by desrever-nu** [evanwong/hipchat-java#16]
I wish I can avoid DEBUG and INFO level log messages.

**Comment by evanwong** [comment]
I am using sfl4j but accidentally added the simple logger to the runtime. 
I will remove the simple logger from the runtime dependencies later but you can use one of the following ways to disable debug and info logging for now. 

`-Dorg.slf4j.simpleLogger.defaultLogLevel=error`

or

`System.setProperty("org.slf4j.simpleLogger.defaultLogLevel", "error")`

**Comment by evanwong** [comment]
And of course after you disable the simpleLogger logging, you can bind it to any logging frameworks that you want to use.

**Comment by desrever-nu** [comment]
ty

**Comment by evanwong** [comment]
Removed the sfl4j simple logger in runtime. Released in v0.3 e953367.
