### ISSUE TITLE
The example given in the README does not work

### ISSUE THREAD

**Issue by ferozed** [evanwong/hipchat-java#21]
hi! 

I am using the example in the readme, but it does not work:

```
        try {
            String defaultAccessToken = "xxxxx";
            HipChatClient client = new HipChatClient(defaultAccessToken);

            SendRoomNotificationRequestBuilder builder = client.prepareSendRoomNotificationRequestBuilder("test", "hello world!");


            Future<NoContent> future = builder.setColor(MessageColor.YELLOW).setNotify(true).build().execute();
//optional... if you want/need to inspect the result:
            NoContent noContent = future.get();
        } catch(Exception e) {
            LOG.error("exception", e);
        }

```

this is returning:

```
2015-03-13 14:11:29,821 ERROR [-1:?] [io.evanwong.oss.hipchat.v2.commons.PostRequest] Invalid response status: 401, content: {
  "error": {
    "code": 401,
    "message": "Invalid OAuth session",
    "type": "Unauthorized"
  }
}
```

And I do not see any OAUTH related methods on the HipChat client.

how do I get this to work? What am I doing wrong?

**Comment by evanwong** [comment]
Hi, I just ran the tests and it was working.

Are you using the token on your "Account Setting" -> "API Access" (should be for v2 only)? 
The OAUTH part is not implemented yet. But the README example and most other implemented functions don't require OAUTH since you can obtain the API token in the login section on hipchat.com.

**Comment by botouser** [comment]
The token is the 128bit hex string given by the administrator right? If so I tried that, but still doesnt work.

same response: 401, Invalid OAuth session.

**Comment by evanwong** [comment]
No, it is not a hex string. It is more like a random alphanumeric string. You should be able to get it from this page:

![access_token](https://cloud.githubusercontent.com/assets/1258612/6680668/d0e9153e-cc30-11e4-9fbf-51aef25d0b58.png)
