### ISSUE TITLE
Compilation errors in the provided sample code

### ISSUE THREAD

**Issue by buwaneka** [evanwong/hipchat-java#23]
Tried your sample code in the readme file.

String defaultAccessToken = "22222-mytoken";
HipChatClient client = new HipChatClient(defaultAccessToken);
SendRoomNotificationRequestBuilder builder = client.prepareSendRoomNotificationRequestBuilder("room-test-1","this is my first message");
java.util.concurrent.Future<NoContent> future;
future = builder.setColor(MessageColor.YELLOW).setNotify(true).build().execute();

and got the following compilation errors in the last line of code;
	- The type io.evanwong.oss.hipchat.v2.commons.Request cannot be resolved. It is indirectly referenced from 
	 required .class files
	- The method execute() is undefined for the type SendRoomNotificationRequest
![hip-chat-error](https://cloud.githubusercontent.com/assets/3897202/7106074/6e9d6d8e-e153-11e4-9c7d-72bea18e5c8f.png)

quick reply is much appreciated.
thanks in advance.

**Comment by evanwong** [comment]
I am not able to replicate this. Are you using 0.3? 
Also, maybe you can try to clean and rebuild your local .class files and maven dependencies.

    HipChatClient hcc = new HipChatClient("xxxxxxxxxxx");
    SendRoomNotificationRequestBuilder builder = hcc.prepareSendRoomNotificationRequestBuilder("test1", "test threads");
    Future<NoContent> future = builder.setColor(MessageColor.GREEN).setNotify(true).build().execute();
    NoContent noContent = future.get();

**Comment by buwaneka** [comment]
Found out that the issue was with the eclipse (older)version I was using. Now I'm using eclipse luna and the code works fine. Thanks for the reply.
