### ISSUE TITLE
Unrecognized fields should be ignored.

### ISSUE THREAD

**Issue by bmatthias** [evanwong/hipchat-java#30]
In Request.java, this line should be added in order to prevent the client from failing if Atlassian adds new fields:

this.objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);

Currently I am getting this exception:

com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "version" (class io.evanwong.oss.hipchat.v2.rooms.RoomItem), not marked as ignorable (3 known properties: "links", "id", "name"])

**Comment by denen99** [comment]
Seeing the same thing for archived.

com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "is_archived" (class io.evanwong.oss.hipchat.v2.rooms.RoomItem), not marked as ignorable (3 known properties: "links", "id", "name"])

**Comment by orenn76** [comment]
Same here.

After doing:
HipChatClient client = new HipChatClient();
Rooms rooms = client.prepareGetAllRoomsRequestBuilder("View Group token...").build().execute().get();

I get:
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "is_archived" (class io.evanwong.oss.hipchat.v2.rooms.RoomItem), not marked as ignorable (3 known properties: "links", "id", "name"])

**Comment by evanwong** [comment]
Thanks for reporting!
